import {
  Dashboard,
  Settings,
  SystemManagement,
  Seeker,
  CustomerManagement,
  VendorManagement,
  SubAdminManagement,
  ProductManagement,
  WarehouseManagement,
  Taxes,
  Groups,
  GroupTesting,
  Rating,
} from "./Svg";

export const menu = [
  {
    name: "Dashboard",
    path: "/",
    Svg: Dashboard,
    subMenu: [],
    highlight: ["/my-profile", "/change-password"],
    subHighlight: [],
    key: "1",
  },
  {
    name: "Customer Management",
    path: "/customers",
    Svg: CustomerManagement,
    subMenu: [],
    highlight: ["/customer/add"],
    subHighlight: [
      "/customer/view",
      "/customer/edit",
      "/customer/change-password",
    ],
    key: "2",
  },
  {
    name: "Vendor Management",
    path: "/vendors",

    Svg: VendorManagement,
    subMenu: [],
    highlight: ["/vendor/add"],
    subHighlight: ["/vendor/view", "/vendor/edit", "/vendor/change-password"],
    key: "3",
  },
  {
    name: "Sub Admin Management",
    Svg: SubAdminManagement,
    subMenu: [
      {
        name: "Sub Admin",
        path: "/sub-admins",
        highlight: ["/sub-admin/add"],
        subHighlight: [
          "/sub-admin/view",
          "/sub-admin/edit",
          "/sub-admin/change-password",
        ],
        key: "4_1",
        subMenu: [],
      },
      {
        name: "Admin Roles",
        path: "/admin-roles",
        highlight: ["/admin-role/add"],
        subHighlight: ["/admin-role/view", "/admin-role/edit"],
        key: "4_20",
        subMenu: [],
      },
    ],
    highlight: ["/sub-admin/add", "/admin-role/add"],
    subHighlight: [
      "/sub-admin/view",
      "/sub-admin/edit",
      "/sub-admin/change-password",
      "/admin-role/view",
      "/admin-role/edit",
    ],
    key: "4",
  },
  // {
  //   name: "Storefront Subscription Plans",
  //   Svg: Seeker,
  //   subMenu: [
  //     {
  //       name: "Subscription Plans",
  //       path: "/storefront-subscription-plans",
  //       highlight: ["/storefront-subscription-plan/add"],
  //       subHighlight: [
  //         "/storefront-subscription-plan/view",
  //         "/storefront-subscription-plan/edit",
  //       ],
  //       key: "5_1",
  //     },
  //     {
  //       name: "Subscription Offers",
  //       path: "/subscription-offers",
  //       highlight: ["/subscription-offer/add"],
  //       subHighlight: ["/subscription-offer/view", "/subscription-offer/edit"],
  //       key: "5_20",
  //     },
  //   ],
  //   highlight: ["/storefront-subscription-plan/add", "/subscription-offer/add"],
  //   subHighlight: [
  //     "/storefront-subscription-plan/view",
  //     "/storefront-subscription-plan/edit",
  //     "/subscription-offer/view",
  //     "/subscription-offer/edit",
  //   ],
  //   key: "5",
  // },
  {
    name: "Products Management",
    Svg: ProductManagement,
    subMenu: [
      {
        name: "Products",
        path: "/products",
        highlight: ["/product/add"],
        subHighlight: ["/product/view", "/product/edit"],
        key: "6_1",
        subMenu: [],
      },
      {
        name: "Pending Products",
        path: "/pending-products",
        highlight: [],
        subHighlight: [],
        key: "6_1",
        subMenu: [],
      },
      {
        name: "Product Categories",
        path: "/product/categories",
        highlight: ["/product/category/add"],
        subHighlight: [
          "/product/category/view",
          "/product/category/edit",
          "/product/sub-categories",
          "/product/sub-category/add",
        ],
        key: "6_20",
        subMenu: [],
      },
      {
        name: "Variants",
        path: "/variants",
        highlight: ["/variant/add"],
        subHighlight: ["/variant/edit", "/variant/view"],
        key: "12_160",
        subMenu: [],
      },
      {
        name: "Brands",
        path: "/brands",
        highlight: ["/brand/add"],
        subHighlight: ["/brand/edit"],
        key: "12_190",
        subMenu: [],
      },
      {
        name: "Units",
        path: "/units",
        highlight: ["/unit/add"],
        subHighlight: ["/unit/edit"],
        key: "12_190",
        subMenu: [],
      },
      {
        name: "Specification Groups",
        path: "/specification-groups",
        highlight: ["/specification-groups/add"],
        subHighlight: ["/specification-groups/edit"],
        key: "12_191",
        subMenu: [],
      },
      // {
      //   name: "Product Sub Categories",
      //   path: "/product/sub-categories",
      //   highlight: ["/product/sub-category/add"],
      //   subHighlight: [
      //     "/product/sub-category/view",
      //     "/product/sub-category/edit",
      //   ],
      // },
      // {
      //   name: "Product Sponsor/Promotion Package Management",
      //   path: "/promotion-packages",
      //   highlight: ["/promotion-package/add"],
      //   subHighlight: ["/promotion-package/view", "/promotion-package/edit"],
      //   key: "6_60",
      // },
      {
        name: "Reels Management",
        path: "/product-promotional-videos",
        highlight: ["/product-promotional-video/add"],
        subHighlight: [
          "/product-promotional-video/view",
          "/product-promotional-video/edit",
        ],
        key: "6_80",
        subMenu: [],
      },
      {
        name: "Vendor Reels Management",
        path: "/storefront-reels",
        highlight: [],
        subHighlight: [],
        key: "6_81",
        subMenu: [],
      },
      // {
      //   name: "Warehouse Management",
      //   path: "/warehouses",
      //   highlight: ["/warehouse/add"],
      //   subHighlight: ["/warehouse/view", "/warehouse/edit"],
      //   key: "12_200",
      // },
      {
        name: "Manufactures Management",
        path: "/manufactures",
        highlight: ["/manufacture/add"],
        subHighlight: ["/manufacture/view", "/manufacture/edit"],
        key: "15",
        subMenu: [],
      },
      {
        name: "Sync List",
        path: "/product-sync",
        highlight: [],
        subHighlight: [
          "/product-sync/view",
          "/product-sync/edit",
          "/product-sync/history",
        ],
        key: "16",
        subMenu: [],
      },
    ],
    highlight: [
      "/product/add",
      "/product/category/add",
      "/promotion-package/add",
    ],
    subHighlight: [
      "/product/view",
      "/product/edit",
      "/product/category/view",
      "/product/category/edit",
      "/promotion-package/view",
      "/promotion-package/edit",
      "/product/sub-categories",
      "/product/sub-category/add",
      "/variant/edit",
      "/brand/edit",
      "/unit/edit",
      "/manufacture/view",
      "/manufacture/edit",
    ],
    key: "6",
  },

  {
    name: "Warehouse Management",
    Svg: WarehouseManagement,
    subMenu: [
      {
        name: "Warehouses",
        path: "/warehouses",
        highlight: ["/warehouse/add"],
        subHighlight: [
          "/warehouse/edit",
          "/warehouse/view",
          "/warehouse/products",
          "/warehouse/logs",
          "/warehouse/add-products",
          "/warehouse/inventory-reports",
          "/warehouses/inventory-report/add",
          "/warehouses/inventory-report/view",
        ],
        key: "7_1",
        subMenu: [],
      },
      {
        name: "Warehouse Products",
        path: "/warehouse/products",
        highlight: [],
        subHighlight: [],
        key: "7_21",
        subMenu: [],
      },
      {
        name: "Transactions",
        path: "/warehouse/transactions",
        highlight: ["/warehouse/transfer"],
        subHighlight: [],
        key: "7_20",
        subMenu: [],
      },
    ],
    highlight: ["/warehouse/add"],
    subHighlight: [
      "/warehouse/view",
      "/warehouse/edit",
      "/warehouse/products",
      "/warehouse/add-products",
      "/warehouse/logs",
      "/warehouse/inventory-reports",
      "/warehouses/inventory-report/add",
      "/warehouses/inventory-report/view",
    ],
    key: "7",
  },
  {
    name: "Orders Management",
    path: "/order/all",
    Svg: CustomerManagement,
    subMenu: [],
    highlight: ["/order/all", "/order/view"],
    subHighlight: ["/order/all", "/order/view"],
    key: "7",
  },
  {
    name: "Review Management",
    path: "/reviews",
    Svg: Rating,
    subMenu: [],
    highlight: ["/reviews", "/reviews/edit"],
    subHighlight: ["/reviews", "/reviews/edit"],
    key: "7",
  },
  {
    name: "Transaction Management",
    path: "/transaction",
    Svg: WarehouseManagement,
    subMenu: [],
    highlight: ["/transaction"],
    subHighlight: [],
    key: "14",
  },

  {
    name: "Shipping Companies Management",
    path: "/shipping-companies",
    Svg: WarehouseManagement,
    subMenu: [],
    highlight: ["/shipping-company/add"],
    subHighlight: [
      "/warehouse/view",
      "/shipping-company/edit",
      "/shipping-company/area",
      "/shipping-company/price",
    ],
    key: "8",
  },
  // {
  //   name: "Manufactures Management",
  //   path: "/manufactures",
  //   Svg: Taxes,
  //   subMenu: [],
  //   highlight: ["/manufacture/add"],
  //   subHighlight: ["/manufacture/view", "/manufacture/edit"],
  //   key: "15",
  // },
  {
    name: "Requested Categories",
    path: "/requested-categories",
    Svg: Dashboard,
    subMenu: [],
    highlight: [],
    subHighlight: [],
    key: "14",
  },
  // {
  //   name: "Groups",

  //   Svg: Groups,
  //   subMenu: [
  //     {
  //       name: "Vendors",
  //       path: "/group/vendors",
  //       highlight: ["/group/vendor/add"],
  //       subHighlight: ["/group/vendor/edit", "/group/vendor/view"],
  //       key: "18_21",
  //     },
  //     {
  //       name: "Countries",
  //       path: "/group/countries",
  //       highlight: ["/group/country/add"],
  //       subHighlight: ["/group/country/edit", "/group/country/view"],

  //       key: "18_22",
  //     },
  //     {
  //       name: "Customers",
  //       path: "/group/customers",
  //       highlight: ["/group/customer/add"],
  //       subHighlight: ["/group/customer/edit", "/group/customer/view"],
  //       key: "18_23",
  //     },

  //     {
  //       name: "Suppliers",
  //       path: "/group/suppliers",
  //       highlight: ["/group/supplier/add"],
  //       subHighlight: ["/group/supplier/edit", "/group/supplier/view"],
  //       key: "18_24",
  //     },

  //     {
  //       name: "Products ",
  //       path: "/group/products",
  //       highlight: ["/group/product/add"],
  //       subHighlight: ["/group/product/edit", "/group/product/view"],
  //       key: "18_25",
  //     },
  //   ],
  //   highlight: [
  //     // "/group/vendor/add",
  //     // "/group/country/add",
  //     // "/group/customer/add",
  //     // "/group/supplier/add",
  //     // "/group/product/add",
  //   ],
  //   subHighlight: [
  //     "/group/vendor/edit",
  //     "/group/vendor/view",
  //     "/group/country/edit",
  //     "/group/country/view",
  //     "/group/customer/edit",
  //     "/group/customer/view",
  //     "/group/supplier/edit",
  //     "/group/supplier/view",
  //     "/group/product/edit",
  //     "/group/product // {
  //   name: "Groups",

  //   Svg: Groups,
  //   subMenu: [
  //     {
  //       name: "Vendors",
  //       path: "/group/vendors",
  //       highlight: ["/group/vendor/add"],
  //       subHighlight: ["/group/vendor/edit", "/group/vendor/view"],
  //       key: "18_21",
  //     },
  //     {
  //       name: "Countries",
  //       path: "/group/countries",
  //       highlight: ["/group/country/add"],
  //       subHighlight: ["/group/country/edit", "/group/country/view"],

  //       key: "18_22",
  //     },
  //     {
  //       name: "Customers",
  //       path: "/group/customers",
  //       highlight: ["/group/customer/add"],
  //       subHighlight: ["/group/customer/edit", "/group/customer/view"],
  //       key: "18_23",
  //     },

  //     {
  //       name: "Suppliers",
  //       path: "/group/suppliers",
  //       highlight: ["/group/supplier/add"],
  //       subHighlight: ["/group/supplier/edit", "/group/supplier/view"],
  //       key: "18_24",
  //     },

  //     {
  //       name: "Products ",
  //       path: "/group/products",
  //       highlight: ["/group/product/add"],
  //       subHighlight:/view",
  //   ],

  //   key: "18",
  // },

  // {
  //   name: "Country Pricing",
  //   Svg: Groups,
  //   subMenu: [
  //     {
  //       name: "Category Pricing",
  //       path: "/country-pricing/category",
  //       highlight: ["/country-pricing/category/add"],
  //       subHighlight: [
  //         "/country-pricing/category/add",
  //         "/country-pricing/category/view",
  //         "/country-pricing/category/edit",
  //       ],
  //       key: "22_21",
  //       subMenu: [],
  //     },
  //     {
  //       name: "Customers Group Pricing",
  //       path: "/country-pricing/customer",
  //       highlight: ["/country-pricing/customer/add"],
  //       subHighlight: [
  //         "/country-pricing/customer/add",
  //         "/country-pricing/customer/view",
  //         "/country-pricing/customer/edit",
  //       ],
  //       key: "22_22",
  //       subMenu: [],
  //     },
  //     {
  //       name: "Products Group Pricing",
  //       path: "/country-pricing/product",
  //       highlight: ["/country-pricing/product/add"],
  //       subHighlight: [
  //         "/country-pricing/product/add",
  //         "/country-pricing/product/view",
  //         "/country-pricing/product/edit",
  //       ],
  //       key: "22_23",
  //       subMenu: [],
  //     },
  //     {
  //       name: "Product Pricing",
  //       path: "/country-pricing/specific",
  //       highlight: ["/country-pricing/specific/add"],
  //       subHighlight: [
  //         "/country-pricing/specific/add",
  //         "/country-pricing/specific/view",
  //         "/country-pricing/specific/edit",
  //       ],
  //       key: "22_24",
  //       subMenu: [],
  //     },
  //   ],
  //   highlight: [],
  //   subHighlight: [
  //     "/country-pricing/category/add",
  //     "/country-pricing/category/view",
  //     "/country-pricing/category/edit",
  //     "/country-pricing/customer/add",
  //     "/country-pricing/customer/view",
  //     "/country-pricing/customer/edit",
  //     "/country-pricing/product/add",
  //     "/country-pricing/product/view",
  //     "/country-pricing/product/edit",
  //     "/country-pricing/specific/add",
  //     "/country-pricing/specific/view",
  //     "/country-pricing/specific/edit",
  //   ],

  //   key: "22",
  // },
  {
    name: "Pricing Setting",
    Svg: Groups,
    subMenu: [
      {
        name: "System Pricing",
        // Svg: Groups,
        subMenu: [
          {
            name: "Category Pricing",
            path: "/system-pricing/category",
            highlight: ["/system-pricing/category/add"],
            subHighlight: [
              "/system-pricing/category/add",
              "/system-pricing/category/view",
              "/system-pricing/category/edit",
            ],
            key: "25_21",
            subMenu: [],
          },

          {
            name: "Product Group Pricing",
            path: "/system-pricing/product",
            highlight: ["/system-pricing/product"],
            subHighlight: [
              "/system-pricing/product/add",
              "/system-pricing/product/view",
              "/system-pricing/product/edit",
            ],
            key: "25_23",
            subMenu: [],
          },
          {
            name: "Customer Group Pricing",
            path: "/system-pricing/customer",
            highlight: ["/system-pricing/customer"],
            subHighlight: [
              "/system-pricing/customer/add",
              "/system-pricing/customer/view",
              "/system-pricing/customer/edit",
            ],
            key: "25_22",
            subMenu: [],
          },
        ],
        highlight: [],
        subHighlight: [
          "/system-pricing/category/add",
          "/system-pricing/category/view",
          "/system-pricing/category/edit",
          "/system-pricing/customer/add",
          "/system-pricing/customer/view",
          "/system-pricing/customer/edit",
          "/system-pricing/product/add",
          "/system-pricing/product/view",
          "/system-pricing/product/edit",
        ],

        key: "20",
      },
      {
        name: "Country Pricing",
        path: "/country-pricing",
        highlight: ["/country-pricing"],
        subHighlight: [
          "/country-pricing/data",
          "/country-pricing/category/add",
          "/country-pricing/category/edit",
        ],
        key: "20_24",
        subMenu: [],
      },
      {
        name: "Payment Methods",
        path: "/pricing-setting/payment-methods",
        highlight: ["/pricing-setting/payment-methods"],
        subHighlight: [
          "/pricing-setting/payment-methods",
          "/pricing-setting/payment-methods/edit",
        ],
        key: "20_24",
        subMenu: [],
      },
      {
        name: "Banks ",
        path: "/pricing-setting/banks",
        highlight: ["/pricing-setting/bank/add"],
        subHighlight: [
          "/pricing-setting/bank/add",
          "/pricing-setting/bank/edit",
          "/pricing-setting/bank/view",
          "/pricing-setting/bank/account",
          "/pricing-setting/bank/account/add",
          "/pricing-setting/bank/account/view",
          "/pricing-setting/bank/account/edit",
        ],
        key: "20_25",
        subMenu: [],
      },
    ],
    highlight: [],
    subHighlight: [
      "/pricing-setting/payment-methods",
      "/pricing-setting/banks",
      "/pricing-setting/bank/add",
      "/pricing-setting/bank/edit",
      "/pricing-setting/payment-methods/edit",
      "/pricing-setting/bank/view",
      "/pricing-setting/bank/account",
      "/pricing-setting/bank/account/add",
      "/pricing-setting/bank/account/view",
      "/pricing-setting/bank/account/edit",
    ],

    key: "20",
  },

  {
    name: "Group",
    Svg: GroupTesting,
    subMenu: [
      {
        name: "Vendors",
        path: "/group/vendors",
        highlight: ["/group/vendor/add"],
        subHighlight: ["/group/vendor/edit", "/group/vendor/view"],
        key: "31_21",
        subMenu: [],
      },
      {
        name: "Countries",
        path: "/group/countries",
        highlight: ["/group/country/add"],
        subHighlight: ["/group/country/edit", "/group/country/view"],

        key: "31_22",
        subMenu: [],
      },
      {
        name: "Customers",
        path: "/group/customers",
        highlight: ["/group/customer/add"],
        subHighlight: ["/group/customer/edit", "/group/customer/view"],
        key: "31_23",
        subMenu: [],
      },

      {
        name: "Suppliers",
        path: "/group/suppliers",
        highlight: ["/group/supplier/add"],
        subHighlight: ["/group/supplier/edit", "/group/supplier/view"],
        key: "31_24",
        subMenu: [],
      },

      {
        name: "Products ",
        path: "/group/products",
        highlight: ["/group/product/add"],
        subHighlight: ["/group/product/edit", "/group/product/view"],
        key: "31_25",
        subMenu: [],
      },
    ],
    highlight: [
      "/group/vendor/add",
      "/group/country/add",
      "/group/customer/add",
      "/group/supplier/add",
      "/group/product/add",
    ],
    subHighlight: [
      "/group/vendor/edit",
      "/group/vendor/view",
      "/group/country/edit",
      "/group/country/view",
      "/group/customer/edit",
      "/group/customer/view",
      "/group/supplier/edit",
      "/group/supplier/view",
      "/group/product/edit",
      "/group/product/view",
    ],
    key: "31",
  },
  {
    name: "Home Page Management",
    Svg: ProductManagement,
    subMenu: [
      {
        name: "Section One",
        path: "/section-one/sliders",
        highlight: [
          "/section-one/sliders",
          "/section-one",
          "/section-one/slider/add",
        ],
        subHighlight: ["/section-one/slider/edit"],
        key: "13_1",
        subMenu: [],
      },
      {
        name: "Section Two",
        path: "/section-two",
        highlight: ["/section-two", "/section-two/add"],
        subHighlight: ["/section-two/edit"],
        key: "13_1",
        subMenu: [],
      },
      {
        name: "Section Three",
        path: "/section-three",
        highlight: ["/section-three", "/section-three/add"],
        subHighlight: ["/section-three/edit"],
        key: "13_1",
        subMenu: [],
      },
      {
        name: "Section Four",
        path: "/section-four",
        highlight: ["/section-four"],
        subHighlight: [],
        key: "13_1",
        subMenu: [],
      },
      {
        name: "Section Five",
        path: "/section-five",
        highlight: ["/section-five"],
        subHighlight: [],
        key: "13_1",
        subMenu: [],
      },
    ],
    highlight: [
      "/section-one/sliders",
      "/section-one",
      "/section-one/slider/add",
      "/section-two",
      "/section-two/add",
      "/section-three",
      "/section-three/add",
      "/section-four",
    ],
    subHighlight: [
      "/section-one/slider/edit",
      "/section-two/edit",
      "/section-three/edit",
    ],
    key: "13",
  },

  {
    name: "System Management",
    Svg: SystemManagement,
    subMenu: [
      {
        name: "Cms Pages",
        path: "/cms",
        highlight: ["/cms/add"],
        subHighlight: ["/cms/view", "/cms/edit"],
        key: "12_1",
        subMenu: [],
      },
      {
        name: "Seo Pages",
        path: "/seo-pages",
        highlight: ["/seo-page/add"],
        subHighlight: ["/seo-page/edit"],
        key: "12_10",
        subMenu: [],
      },
      {
        name: "Email Templates",
        path: "/email-template",
        highlight: ["/email-template/add"],
        subHighlight: ["/email-template/edit"],
        key: "12_20",
        subMenu: [],
      },
      {
        name: "Email Logs",
        path: "/email-logs",
        highlight: [],
        subHighlight: [],
        key: "12_30",
        subMenu: [],
      },
      {
        name: "FAQs",
        path: "/faq",
        highlight: ["/faq/add"],
        subHighlight: ["/faq/edit", "/faq/view"],
        key: "12_40",
        subMenu: [],
      },
      {
        name: "System Images",
        path: "/system-images",
        highlight: ["/system-images", "/system-images/add"],
        subHighlight: ["/system-images/edit"],
        key: "12_60",
        subMenu: [],
      },
      {
        name: "Countries",
        path: "/countries",
        highlight: ["/country/add"],
        subHighlight: ["/country/edit", "/cities", "/taxes"],
        key: "12_80",
        subMenu: [],
      },
      // {
      //   name: "Notifications",
      //   path: "/notifications",
      //   highlight: ["/notification/send"],
      //   subHighlight: [],
      //   key: "12_100",
      //   subMenu: [],
      // },
      {
        name: "Notification Templates",
        path: "/notification-templates",
        highlight: ["/notification-template/add"],
        subHighlight: ["/notification-template/edit"],
        key: "12_120",
        subMenu: [],
      },
      {
        name: "Languages",
        path: "/languages",
        highlight: ["/language/add"],
        subHighlight: [],
        key: "12_140",
        subMenu: [],
      },

      {
        name: "Currencies",
        path: "/currencies",
        highlight: ["/currency/add"],
        subHighlight: ["/currency/edit"],
        key: "12_180",
        subMenu: [],
      },

      {
        name: "Contact Us",
        path: "/contact-us",
        highlight: [],
        subHighlight: [],
        key: "12_200",
        subMenu: [],
      },
      {
        name: "Inventory Reasons",
        path: "/inventory-reasons",
        highlight: ["/inventory-reason/add"],
        subHighlight: ["/inventory-reason/edit"],

        key: "12_201",
        subMenu: [],
      },

      {
        name: "Newsletter Subscriptions",
        path: "/newsletter-subscriptions",
        highlight: ["/newsletter-subscriptions", "/newsletter-subscriptions"],
        subHighlight: ["/newsletter-subscriptions"],
        subMenu: [],
      },
    ],
    highlight: [
      "/setting/prefix/Payment",
      "/system-images/add",
      "/country/add",
    ],
    subHighlight: [
      "/system-images/edit",
      "/seo-page/edit",
      "/country/edit",
      "/cities",
      "/taxes",
    ],
    key: "12",
  },
  {
    name: "Settings",
    Svg: Settings,
    subMenu: [
      {
        name: "Site Setting",
        path: "/setting/prefix/Site",
        highlight: [],
        subHighlight: [],
        subMenu: [],
      },
      {
        name: "Reading Setting",
        path: "/setting/prefix/Reading",
        highlight: [],
        subHighlight: [],
        subMenu: [],
      },
      {
        name: "Social Setting",
        path: "/setting/prefix/Social",
        highlight: [],
        subHighlight: [],
        subMenu: [],
      },
      {
        name: "Contact Setting",
        path: "/setting/prefix/Contact",
        highlight: [],
        subHighlight: [],
        subMenu: [],
      },
      {
        name: "Review Setting",
        path: "/setting/prefix/Review",
        highlight: [],
        subHighlight: [],
        subMenu: [],
      },
      {
        name: "Product Setting",
        path: "/setting/prefix/Product",
        highlight: [],
        subHighlight: [],
        subMenu: [],
      },
    ],
    highlight: ["/setting", "/setting/add", "/employee-count/add"],
    subHighlight: ["/setting/edit", "/employee-count/edit"],
    key: "13",
  },
];
