const timezones = [
  {
    value: "Dateline Standard Time",
    abbr: "DST",
    offset: -12,
    isdst: false,
    text: "(UTC-12:00) International Date Line West",
    utc: ["Etc/GMT+12"],
    utcData: "Etc/GMT+12",
  },
  {
    value: "UTC-11",
    abbr: "U",
    offset: -11,
    isdst: false,
    text: "(UTC-11:00) Coordinated Universal Time-11",
    utc: ["Etc/GMT+11", "Pacific/Midway", "Pacific/Niue", "Pacific/Pago_Pago"],
    utcData: "Etc/GMT+11",
  },
  {
    value: "Hawaiian Standard Time",
    abbr: "HST",
    offset: -10,
    isdst: false,
    text: "(UTC-10:00) Hawaii",
    utc: [
      "Etc/GMT+10",
      "Pacific/Honolulu",
      "Pacific/Johnston",
      "Pacific/Rarotonga",
      "Pacific/Tahiti",
    ],
    utcData: "Etc/GMT+10",
  },
  {
    value: "Alaskan Standard Time",
    abbr: "AKDT",
    offset: -8,
    isdst: true,
    text: "(UTC-09:00) Alaska",
    utc: [
      "America/Anchorage",
      "America/Juneau",
      "America/Nome",
      "America/Sitka",
      "America/Yakutat",
    ],
    utcData: "America/Anchorage",
  },
  {
    value: "Pacific Standard Time (Mexico)",
    abbr: "PDT",
    offset: -7,
    isdst: true,
    text: "(UTC-08:00) Baja California",
    utc: ["America/Santa_Isabel"],
    utcData: "America/Santa_Isabel",
  },
  {
    value: "Pacific Daylight Time",
    abbr: "PDT",
    offset: -7,
    isdst: true,
    text: "(UTC-07:00) Pacific Daylight Time (US & Canada)",
    utc: ["America/Los_Angeles", "America/Tijuana", "America/Vancouver"],
    utcData: "America/Los_Angeles",
  },
  {
    value: "Pacific Standard Time",
    abbr: "PST",
    offset: -8,
    isdst: false,
    text: "(UTC-08:00) Pacific Standard Time (US & Canada)",
    utc: [
      "America/Los_Angeles",
      "America/Tijuana",
      "America/Vancouver",
      "PST8PDT",
    ],
    utcData: "America/Tijuana",
  },
  {
    value: "US Mountain Standard Time",
    abbr: "UMST",
    offset: -7,
    isdst: false,
    text: "(UTC-07:00) Arizona",
    utc: [
      "America/Creston",
      "America/Dawson",
      "America/Dawson_Creek",
      "America/Hermosillo",
      "America/Phoenix",
      "America/Whitehorse",
      "Etc/GMT+7",
    ],
    utcData: "America/Creston",
  },
  {
    value: "Mountain Standard Time (Mexico)",
    abbr: "MDT",
    offset: -6,
    isdst: true,
    text: "(UTC-07:00) Chihuahua, La Paz, Mazatlan",
    utc: ["America/Chihuahua", "America/Mazatlan"],
    utcData: "America/Chihuahua",
  },
  {
    value: "Mountain Standard Time",
    abbr: "MDT",
    offset: -6,
    isdst: true,
    text: "(UTC-07:00) Mountain Time (US & Canada)",
    utc: [
      "America/Boise",
      "America/Cambridge_Bay",
      "America/Denver",
      "America/Edmonton",
      "America/Inuvik",
      "America/Ojinaga",
      "America/Yellowknife",
      "MST7MDT",
    ],
    utcData: "America/Boise",
  },
  {
    value: "Central America Standard Time",
    abbr: "CAST",
    offset: -6,
    isdst: false,
    text: "(UTC-06:00) Central America",
    utc: [
      "America/Belize",
      "America/Costa_Rica",
      "America/El_Salvador",
      "America/Guatemala",
      "America/Managua",
      "America/Tegucigalpa",
      "Etc/GMT+6",
      "Pacific/Galapagos",
    ],
    utcData: "America/Belize",
  },
  {
    value: "Central Standard Time",
    abbr: "CDT",
    offset: -5,
    isdst: true,
    text: "(UTC-06:00) Central Time (US & Canada)",
    utc: [
      "America/Chicago",
      "America/Indiana/Knox",
      "America/Indiana/Tell_City",
      "America/Matamoros",
      "America/Menominee",
      "America/North_Dakota/Beulah",
      "America/North_Dakota/Center",
      "America/North_Dakota/New_Salem",
      "America/Rainy_River",
      "America/Rankin_Inlet",
      "America/Resolute",
      "America/Winnipeg",
      "CST6CDT",
    ],
    utcData: "America/Chicago",
  },
  {
    value: "Central Standard Time (Mexico)",
    abbr: "CDT",
    offset: -5,
    isdst: true,
    text: "(UTC-06:00) Guadalajara, Mexico City, Monterrey",
    utc: [
      "America/Bahia_Banderas",
      "America/Cancun",
      "America/Merida",
      "America/Mexico_City",
      "America/Monterrey",
    ],
    utcData: "America/Bahia_Banderas",
  },
  {
    value: "Canada Central Standard Time",
    abbr: "CCST",
    offset: -6,
    isdst: false,
    text: "(UTC-06:00) Saskatchewan",
    utc: ["America/Regina", "America/Swift_Current"],
    utcData: "America/Regina",
  },
  {
    value: "SA Pacific Standard Time",
    abbr: "SPST",
    offset: -5,
    isdst: false,
    text: "(UTC-05:00) Bogota, Lima, Quito",
    utc: [
      "America/Bogota",
      "America/Cayman",
      "America/Coral_Harbour",
      "America/Eirunepe",
      "America/Guayaquil",
      "America/Jamaica",
      "America/Lima",
      "America/Panama",
      "America/Rio_Branco",
      "Etc/GMT+5",
    ],
    utcData: "America/Bogota",
  },
  {
    value: "Eastern Standard Time",
    abbr: "EST",
    offset: -5,
    isdst: false,
    text: "(UTC-05:00) Eastern Time (US & Canada)",
    utc: [
      "America/Detroit",
      "America/Havana",
      "America/Indiana/Petersburg",
      "America/Indiana/Vincennes",
      "America/Indiana/Winamac",
      "America/Iqaluit",
      "America/Kentucky/Monticello",
      "America/Louisville",
      "America/Montreal",
      "America/Nassau",
      "America/New_York",
      "America/Nipigon",
      "America/Pangnirtung",
      "America/Port-au-Prince",
      "America/Thunder_Bay",
      "America/Toronto",
    ],
    utcData: "America/Detroit",
  },
  {
    value: "Eastern Daylight Time",
    abbr: "EDT",
    offset: -4,
    isdst: true,
    text: "(UTC-04:00) Eastern Daylight Time (US & Canada)",
    utc: [
      "America/Detroit",
      "America/Havana",
      "America/Indiana/Petersburg",
      "America/Indiana/Vincennes",
      "America/Indiana/Winamac",
      "America/Iqaluit",
      "America/Kentucky/Monticello",
      "America/Louisville",
      "America/Montreal",
      "America/Nassau",
      "America/New_York",
      "America/Nipigon",
      "America/Pangnirtung",
      "America/Port-au-Prince",
      "America/Thunder_Bay",
      "America/Toronto",
    ],
    utcData: "America/Havana",
  },
  {
    value: "US Eastern Standard Time",
    abbr: "UEDT",
    offset: -5,
    isdst: false,
    text: "(UTC-05:00) Indiana (East)",
    utc: [
      "America/Indiana/Marengo",
      "America/Indiana/Vevay",
      "America/Indianapolis",
    ],
    utcData: "America/Indiana/Marengo",
  },
  {
    value: "Venezuela Standard Time",
    abbr: "VST",
    offset: -4.5,
    isdst: false,
    text: "(UTC-04:30) Caracas",
    utc: ["America/Caracas"],
    utcData: "America/Caracas",
  },
  {
    value: "Paraguay Standard Time",
    abbr: "PYT",
    offset: -4,
    isdst: false,
    text: "(UTC-04:00) Asuncion",
    utc: ["America/Asuncion"],
    utcData: "America/Asuncion",
  },
  {
    value: "Atlantic Standard Time",
    abbr: "ADT",
    offset: -3,
    isdst: true,
    text: "(UTC-04:00) Atlantic Time (Canada)",
    utc: [
      "America/Glace_Bay",
      "America/Goose_Bay",
      "America/Halifax",
      "America/Moncton",
      "America/Thule",
      "Atlantic/Bermuda",
    ],
    utcData: "America/Glace_Bay",
  },
  {
    value: "Central Brazilian Standard Time",
    abbr: "CBST",
    offset: -4,
    isdst: false,
    text: "(UTC-04:00) Cuiaba",
    utc: ["America/Campo_Grande", "America/Cuiaba"],
    utcData: "America/Campo_Grande",
  },
  {
    value: "SA Western Standard Time",
    abbr: "SWST",
    offset: -4,
    isdst: false,
    text: "(UTC-04:00) Georgetown, La Paz, Manaus, San Juan",
    utc: [
      "America/Anguilla",
      "America/Antigua",
      "America/Aruba",
      "America/Barbados",
      "America/Blanc-Sablon",
      "America/Boa_Vista",
      "America/Curacao",
      "America/Dominica",
      "America/Grand_Turk",
      "America/Grenada",
      "America/Guadeloupe",
      "America/Guyana",
      "America/Kralendijk",
      "America/La_Paz",
      "America/Lower_Princes",
      "America/Manaus",
      "America/Marigot",
      "America/Martinique",
      "America/Montserrat",
      "America/Port_of_Spain",
      "America/Porto_Velho",
      "America/Puerto_Rico",
      "America/Santo_Domingo",
      "America/St_Barthelemy",
      "America/St_Kitts",
      "America/St_Lucia",
      "America/St_Thomas",
      "America/St_Vincent",
      "America/Tortola",
      "Etc/GMT+4",
    ],
    utcData: "America/Anguilla",
  },
  {
    value: "Pacific SA Standard Time",
    abbr: "PSST",
    offset: -4,
    isdst: false,
    text: "(UTC-04:00) Santiago",
    utc: ["America/Santiago", "Antarctica/Palmer"],
    utcData: "America/Santiago",
  },
  {
    value: "Newfoundland Standard Time",
    abbr: "NDT",
    offset: -2.5,
    isdst: true,
    text: "(UTC-03:30) Newfoundland",
    utc: ["America/St_Johns"],
    utcData: "America/St_Johns",
  },
  {
    value: "E. South America Standard Time",
    abbr: "ESAST",
    offset: -3,
    isdst: false,
    text: "(UTC-03:00) Brasilia",
    utc: ["America/Sao_Paulo"],
    utcData: "America/Sao_Paulo",
  },
  {
    value: "Argentina Standard Time",
    abbr: "AST",
    offset: -3,
    isdst: false,
    text: "(UTC-03:00) Buenos Aires",
    utc: [
      "America/Argentina/La_Rioja",
      "America/Argentina/Rio_Gallegos",
      "America/Argentina/Salta",
      "America/Argentina/San_Juan",
      "America/Argentina/San_Luis",
      "America/Argentina/Tucuman",
      "America/Argentina/Ushuaia",
      "America/Buenos_Aires",
      "America/Catamarca",
      "America/Cordoba",
      "America/Jujuy",
      "America/Mendoza",
    ],
    utcData: "America/Argentina/La_Rioja",
  },
  {
    value: "SA Eastern Standard Time",
    abbr: "SEST",
    offset: -3,
    isdst: false,
    text: "(UTC-03:00) Cayenne, Fortaleza",
    utc: [
      "America/Araguaina",
      "America/Belem",
      "America/Cayenne",
      "America/Fortaleza",
      "America/Maceio",
      "America/Paramaribo",
      "America/Recife",
      "America/Santarem",
      "Antarctica/Rothera",
      "Atlantic/Stanley",
      "Etc/GMT+3",
    ],
    utcData: "America/Araguaina",
  },
  {
    value: "Greenland Standard Time",
    abbr: "GDT",
    offset: -3,
    isdst: true,
    text: "(UTC-03:00) Greenland",
    utc: ["America/Godthab"],
    utcData: "America/Godthab",
  },
  {
    value: "Montevideo Standard Time",
    abbr: "MST",
    offset: -3,
    isdst: false,
    text: "(UTC-03:00) Montevideo",
    utc: ["America/Montevideo"],
    utcData: "America/Montevideo",
  },
  {
    value: "Bahia Standard Time",
    abbr: "BST",
    offset: -3,
    isdst: false,
    text: "(UTC-03:00) Salvador",
    utc: ["America/Bahia"],
    utcData: "America/Bahia",
  },
  {
    value: "UTC-02",
    abbr: "U",
    offset: -2,
    isdst: false,
    text: "(UTC-02:00) Coordinated Universal Time-02",
    utc: ["America/Noronha", "Atlantic/South_Georgia", "Etc/GMT+2"],
    utcData: "America/Noronha",
  },
  {
    value: "Mid-Atlantic Standard Time",
    abbr: "MDT",
    offset: -1,
    isdst: true,
    text: "(UTC-02:00) Mid-Atlantic - Old",
    utc: [],
  },
  {
    value: "Azores Standard Time",
    abbr: "ADT",
    offset: 0,
    isdst: true,
    text: "(UTC-01:00) Azores",
    utc: ["America/Scoresbysund", "Atlantic/Azores"],
    utcData: "America/Scoresbysund",
  },
  {
    value: "Cape Verde Standard Time",
    abbr: "CVST",
    offset: -1,
    isdst: false,
    text: "(UTC-01:00) Cape Verde Is.",
    utc: ["Atlantic/Cape_Verde", "Etc/GMT+1"],
    utcData: "Atlantic/Cape_Verde",
  },
  {
    value: "Morocco Standard Time",
    abbr: "MDT",
    offset: 1,
    isdst: true,
    text: "(UTC+00:00) Casablanca",
    utc: ["Africa/Casablanca", "Africa/El_Aaiun"],
    utcData: "Africa/Casablanca",
  },
  {
    value: "UTC",
    abbr: "UTC",
    offset: 0,
    isdst: false,
    text: "(UTC+00:00) Coordinated Universal Time",
    utc: ["America/Danmarkshavn", "Etc/GMT"],
    utcData: "America/Danmarkshavn",
  },
  {
    value: "GMT Standard Time",
    abbr: "GMT",
    offset: 0,
    isdst: false,
    text: "(UTC+00:00) Edinburgh, London",
    utc: [
      "Europe/Isle_of_Man",
      "Europe/Guernsey",
      "Europe/Jersey",
      "Europe/London",
    ],
    utcData: "Europe/Isle_of_Man",
  },
  {
    value: "British Summer Time",
    abbr: "BST",
    offset: 1,
    isdst: true,
    text: "(UTC+01:00) Edinburgh, London",
    utc: [
      "Europe/Isle_of_Man",
      "Europe/Guernsey",
      "Europe/Jersey",
      "Europe/London",
    ],
    utcData: "Europe/Guernsey",
  },
  {
    value: "GMT Standard Time",
    abbr: "GDT",
    offset: 1,
    isdst: true,
    text: "(UTC+00:00) Dublin, Lisbon",
    utc: [
      "Atlantic/Canary",
      "Atlantic/Faeroe",
      "Atlantic/Madeira",
      "Europe/Dublin",
      "Europe/Lisbon",
    ],
    utcData: "Atlantic/Canary",
  },
  {
    value: "Greenwich Standard Time",
    abbr: "GST",
    offset: 0,
    isdst: false,
    text: "(UTC+00:00) Monrovia, Reykjavik",
    utc: [
      "Africa/Abidjan",
      "Africa/Accra",
      "Africa/Bamako",
      "Africa/Banjul",
      "Africa/Bissau",
      "Africa/Conakry",
      "Africa/Dakar",
      "Africa/Freetown",
      "Africa/Lome",
      "Africa/Monrovia",
      "Africa/Nouakchott",
      "Africa/Ouagadougou",
      "Africa/Sao_Tome",
      "Atlantic/Reykjavik",
      "Atlantic/St_Helena",
    ],
    utcData: "Africa/Abidjan",
  },
  {
    value: "W. Europe Standard Time",
    abbr: "WEDT",
    offset: 2,
    isdst: true,
    text: "(UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna",
    utc: [
      "Arctic/Longyearbyen",
      "Europe/Amsterdam",
      "Europe/Andorra",
      "Europe/Berlin",
      "Europe/Busingen",
      "Europe/Gibraltar",
      "Europe/Luxembourg",
      "Europe/Malta",
      "Europe/Monaco",
      "Europe/Oslo",
      "Europe/Rome",
      "Europe/San_Marino",
      "Europe/Stockholm",
      "Europe/Vaduz",
      "Europe/Vatican",
      "Europe/Vienna",
      "Europe/Zurich",
    ],
    utcData: "Arctic/Longyearbyen",
  },
  {
    value: "Central Europe Standard Time",
    abbr: "CEDT",
    offset: 2,
    isdst: true,
    text: "(UTC+01:00) Belgrade, Bratislava, Budapest, Ljubljana, Prague",
    utc: [
      "Europe/Belgrade",
      "Europe/Bratislava",
      "Europe/Budapest",
      "Europe/Ljubljana",
      "Europe/Podgorica",
      "Europe/Prague",
      "Europe/Tirane",
    ],
    utcData: "Europe/Belgrade",
  },
  {
    value: "Romance Standard Time",
    abbr: "RDT",
    offset: 2,
    isdst: true,
    text: "(UTC+01:00) Brussels, Copenhagen, Madrid, Paris",
    utc: [
      "Africa/Ceuta",
      "Europe/Brussels",
      "Europe/Copenhagen",
      "Europe/Madrid",
      "Europe/Paris",
    ],
    utcData: "Africa/Ceuta",
  },
  {
    value: "Central European Standard Time",
    abbr: "CEDT",
    offset: 2,
    isdst: true,
    text: "(UTC+01:00) Sarajevo, Skopje, Warsaw, Zagreb",
    utc: ["Europe/Sarajevo", "Europe/Skopje", "Europe/Warsaw", "Europe/Zagreb"],
    utcData: "Europe/Sarajevo",
  },
  {
    value: "W. Central Africa Standard Time",
    abbr: "WCAST",
    offset: 1,
    isdst: false,
    text: "(UTC+01:00) West Central Africa",
    utc: [
      "Africa/Algiers",
      "Africa/Bangui",
      "Africa/Brazzaville",
      "Africa/Douala",
      "Africa/Kinshasa",
      "Africa/Lagos",
      "Africa/Libreville",
      "Africa/Luanda",
      "Africa/Malabo",
      "Africa/Ndjamena",
      "Africa/Niamey",
      "Africa/Porto-Novo",
      "Africa/Tunis",
      "Etc/GMT-1",
    ],
    utcData: "Africa/Algiers",
  },
  {
    value: "Namibia Standard Time",
    abbr: "NST",
    offset: 1,
    isdst: false,
    text: "(UTC+01:00) Windhoek",
    utc: ["Africa/Windhoek"],
    utcData: "Africa/Windhoek",
  },
  {
    value: "GTB Standard Time",
    abbr: "GDT",
    offset: 3,
    isdst: true,
    text: "(UTC+02:00) Athens, Bucharest",
    utc: [
      "Asia/Nicosia",
      "Europe/Athens",
      "Europe/Bucharest",
      "Europe/Chisinau",
    ],
    utcData: "Asia/Nicosia",
  },
  {
    value: "Middle East Standard Time",
    abbr: "MEDT",
    offset: 3,
    isdst: true,
    text: "(UTC+02:00) Beirut",
    utc: ["Asia/Beirut"],
    utcData: "Asia/Beirut",
  },
  {
    value: "Egypt Standard Time",
    abbr: "EST",
    offset: 2,
    isdst: false,
    text: "(UTC+02:00) Cairo",
    utc: ["Africa/Cairo"],
    utcData: "Africa/Cairo",
  },
  {
    value: "Syria Standard Time",
    abbr: "SDT",
    offset: 3,
    isdst: true,
    text: "(UTC+02:00) Damascus",
    utc: ["Asia/Damascus"],
    utcData: "Asia/Damascus",
  },
  {
    value: "E. Europe Standard Time",
    abbr: "EEDT",
    offset: 3,
    isdst: true,
    text: "(UTC+02:00) E. Europe",
    utc: [
      "Asia/Nicosia",
      "Europe/Athens",
      "Europe/Bucharest",
      "Europe/Chisinau",
      "Europe/Helsinki",
      "Europe/Kiev",
      "Europe/Mariehamn",
      "Europe/Nicosia",
      "Europe/Riga",
      "Europe/Sofia",
      "Europe/Tallinn",
      "Europe/Uzhgorod",
      "Europe/Vilnius",
      "Europe/Zaporozhye",
    ],
    utcData: "Europe/Athens",
  },
  {
    value: "South Africa Standard Time",
    abbr: "SAST",
    offset: 2,
    isdst: false,
    text: "(UTC+02:00) Harare, Pretoria",
    utc: [
      "Africa/Blantyre",
      "Africa/Bujumbura",
      "Africa/Gaborone",
      "Africa/Harare",
      "Africa/Johannesburg",
      "Africa/Kigali",
      "Africa/Lubumbashi",
      "Africa/Lusaka",
      "Africa/Maputo",
      "Africa/Maseru",
      "Africa/Mbabane",
      "Etc/GMT-2",
    ],
    utcData: "Africa/Blantyre",
  },
  {
    value: "FLE Standard Time",
    abbr: "FDT",
    offset: 3,
    isdst: true,
    text: "(UTC+02:00) Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius",
    utc: [
      "Europe/Helsinki",
      "Europe/Kiev",
      "Europe/Mariehamn",
      "Europe/Riga",
      "Europe/Sofia",
      "Europe/Tallinn",
      "Europe/Uzhgorod",
      "Europe/Vilnius",
      "Europe/Zaporozhye",
    ],
    utcData: "Europe/Helsinki",
  },
  {
    value: "Turkey Standard Time",
    abbr: "TDT",
    offset: 3,
    isdst: false,
    text: "(UTC+03:00) Istanbul",
    utc: ["Europe/Istanbul"],
    utcData: "Europe/Istanbul",
  },
  {
    value: "Israel Standard Time",
    abbr: "JDT",
    offset: 3,
    isdst: true,
    text: "(UTC+02:00) Jerusalem",
    utc: ["Asia/Jerusalem"],
    utcData: "Asia/Jerusalem",
  },
  {
    value: "Libya Standard Time",
    abbr: "LST",
    offset: 2,
    isdst: false,
    text: "(UTC+02:00) Tripoli",
    utc: ["Africa/Tripoli"],
    utcData: "Africa/Tripoli",
  },
  {
    value: "Jordan Standard Time",
    abbr: "JST",
    offset: 3,
    isdst: false,
    text: "(UTC+03:00) Amman",
    utc: ["Asia/Amman"],
    utcData: "Asia/Amman",
  },
  {
    value: "Arabic Standard Time",
    abbr: "AST",
    offset: 3,
    isdst: false,
    text: "(UTC+03:00) Baghdad",
    utc: ["Asia/Baghdad"],
    utcData: "Asia/Baghdad",
  },
  {
    value: "Kaliningrad Standard Time",
    abbr: "KST",
    offset: 3,
    isdst: false,
    text: "(UTC+02:00) Kaliningrad",
    utc: ["Europe/Kaliningrad"],
    utcData: "Europe/Kaliningrad",
  },
  {
    value: "Arab Standard Time",
    abbr: "AST",
    offset: 3,
    isdst: false,
    text: "(UTC+03:00) Kuwait, Riyadh",
    utc: [
      "Asia/Aden",
      "Asia/Bahrain",
      "Asia/Kuwait",
      "Asia/Qatar",
      "Asia/Riyadh",
    ],
    utcData: "Asia/Aden",
  },
  {
    value: "E. Africa Standard Time",
    abbr: "EAST",
    offset: 3,
    isdst: false,
    text: "(UTC+03:00) Nairobi",
    utc: [
      "Africa/Addis_Ababa",
      "Africa/Asmera",
      "Africa/Dar_es_Salaam",
      "Africa/Djibouti",
      "Africa/Juba",
      "Africa/Kampala",
      "Africa/Khartoum",
      "Africa/Mogadishu",
      "Africa/Nairobi",
      "Antarctica/Syowa",
      "Etc/GMT-3",
      "Indian/Antananarivo",
      "Indian/Comoro",
      "Indian/Mayotte",
    ],
    utcData: "Africa/Addis_Ababa",
  },
  {
    value: "Moscow Standard Time",
    abbr: "MSK",
    offset: 3,
    isdst: false,
    text: "(UTC+03:00) Moscow, St. Petersburg, Volgograd, Minsk",
    utc: [
      "Europe/Kirov",
      "Europe/Moscow",
      "Europe/Simferopol",
      "Europe/Volgograd",
      "Europe/Minsk",
    ],
    utcData: "Europe/Kirov",
  },
  {
    value: "Samara Time",
    abbr: "SAMT",
    offset: 4,
    isdst: false,
    text: "(UTC+04:00) Samara, Ulyanovsk, Saratov",
    utc: ["Europe/Astrakhan", "Europe/Samara", "Europe/Ulyanovsk"],
    utcData: "Europe/Astrakhan",
  },
  {
    value: "Iran Standard Time",
    abbr: "IDT",
    offset: 4.5,
    isdst: true,
    text: "(UTC+03:30) Tehran",
    utc: ["Asia/Tehran"],
    utcData: "Asia/Tehran",
  },
  {
    value: "Arabian Standard Time",
    abbr: "AST",
    offset: 4,
    isdst: false,
    text: "(UTC+04:00) Abu Dhabi, Muscat",
    utc: ["Asia/Dubai", "Asia/Muscat", "Etc/GMT-4"],
    utcData: "Asia/Dubai",
  },
  {
    value: "Azerbaijan Standard Time",
    abbr: "ADT",
    offset: 5,
    isdst: true,
    text: "(UTC+04:00) Baku",
    utc: ["Asia/Baku"],
    utcData: "Asia/Baku",
  },
  {
    value: "Mauritius Standard Time",
    abbr: "MST",
    offset: 4,
    isdst: false,
    text: "(UTC+04:00) Port Louis",
    utc: ["Indian/Mahe", "Indian/Mauritius", "Indian/Reunion"],
    utcData: "Indian/Mahe",
  },
  {
    value: "Georgian Standard Time",
    abbr: "GET",
    offset: 4,
    isdst: false,
    text: "(UTC+04:00) Tbilisi",
    utc: ["Asia/Tbilisi"],
    utcData: "Asia/Tbilisi",
  },
  {
    value: "Caucasus Standard Time",
    abbr: "CST",
    offset: 4,
    isdst: false,
    text: "(UTC+04:00) Yerevan",
    utc: ["Asia/Yerevan"],
    utcData: "Asia/Yerevan",
  },
  {
    value: "Afghanistan Standard Time",
    abbr: "AST",
    offset: 4.5,
    isdst: false,
    text: "(UTC+04:30) Kabul",
    utc: ["Asia/Kabul"],
    utcData: "Asia/Kabul",
  },
  {
    value: "West Asia Standard Time",
    abbr: "WAST",
    offset: 5,
    isdst: false,
    text: "(UTC+05:00) Ashgabat, Tashkent",
    utc: [
      "Antarctica/Mawson",
      "Asia/Aqtau",
      "Asia/Aqtobe",
      "Asia/Ashgabat",
      "Asia/Dushanbe",
      "Asia/Oral",
      "Asia/Samarkand",
      "Asia/Tashkent",
      "Etc/GMT-5",
      "Indian/Kerguelen",
      "Indian/Maldives",
    ],
    utcData: "Antarctica/Mawson",
  },
  {
    value: "Yekaterinburg Time",
    abbr: "YEKT",
    offset: 5,
    isdst: false,
    text: "(UTC+05:00) Yekaterinburg",
    utc: ["Asia/Yekaterinburg"],
    utcData: "Asia/Yekaterinburg",
  },
  {
    value: "Pakistan Standard Time",
    abbr: "PKT",
    offset: 5,
    isdst: false,
    text: "(UTC+05:00) Islamabad, Karachi",
    utc: ["Asia/Karachi"],
    utcData: "Asia/Karachi",
  },
  {
    value: "India Standard Time",
    abbr: "IST",
    offset: 5.5,
    isdst: false,
    text: "(UTC+05:30) Chennai, Kolkata, Mumbai, New Delhi",
    utc: ["Asia/Kolkata", "Asia/Calcutta"],
    utcData: "Asia/Kolkata",
  },
  {
    value: "Sri Lanka Standard Time",
    abbr: "SLST",
    offset: 5.5,
    isdst: false,
    text: "(UTC+05:30) Sri Jayawardenepura",
    utc: ["Asia/Colombo"],
    utcData: "Asia/Colombo",
  },
  {
    value: "Nepal Standard Time",
    abbr: "NST",
    offset: 5.75,
    isdst: false,
    text: "(UTC+05:45) Kathmandu",
    utc: ["Asia/Kathmandu"],
    utcData: "Asia/Kathmandu",
  },
  {
    value: "Central Asia Standard Time",
    abbr: "CAST",
    offset: 6,
    isdst: false,
    text: "(UTC+06:00) Nur-Sultan (Astana)",
    utc: [
      "Antarctica/Vostok",
      "Asia/Almaty",
      "Asia/Bishkek",
      "Asia/Qyzylorda",
      "Asia/Urumqi",
      "Etc/GMT-6",
      "Indian/Chagos",
    ],
    utcData: "Antarctica/Vostok",
  },
  {
    value: "Bangladesh Standard Time",
    abbr: "BST",
    offset: 6,
    isdst: false,
    text: "(UTC+06:00) Dhaka",
    utc: ["Asia/Dhaka", "Asia/Thimphu"],
    utcData: "Asia/Dhaka",
  },
  {
    value: "Myanmar Standard Time",
    abbr: "MST",
    offset: 6.5,
    isdst: false,
    text: "(UTC+06:30) Yangon (Rangoon)",
    utc: ["Asia/Rangoon", "Indian/Cocos"],
    utcData: "Asia/Rangoon",
  },
  {
    value: "SE Asia Standard Time",
    abbr: "SAST",
    offset: 7,
    isdst: false,
    text: "(UTC+07:00) Bangkok, Hanoi, Jakarta",
    utc: [
      "Antarctica/Davis",
      "Asia/Bangkok",
      "Asia/Hovd",
      "Asia/Jakarta",
      "Asia/Phnom_Penh",
      "Asia/Pontianak",
      "Asia/Saigon",
      "Asia/Vientiane",
      "Etc/GMT-7",
      "Indian/Christmas",
    ],
    utcData: "Antarctica/Davis",
  },
  {
    value: "N. Central Asia Standard Time",
    abbr: "NCAST",
    offset: 7,
    isdst: false,
    text: "(UTC+07:00) Novosibirsk",
    utc: ["Asia/Novokuznetsk", "Asia/Novosibirsk", "Asia/Omsk"],
    utcData: "Asia/Novokuznetsk",
  },
  {
    value: "China Standard Time",
    abbr: "CST",
    offset: 8,
    isdst: false,
    text: "(UTC+08:00) Beijing, Chongqing, Hong Kong, Urumqi",
    utc: ["Asia/Hong_Kong", "Asia/Macau", "Asia/Shanghai"],
    utcData: "Asia/Hong_Kong",
  },
  {
    value: "North Asia Standard Time",
    abbr: "NAST",
    offset: 8,
    isdst: false,
    text: "(UTC+08:00) Krasnoyarsk",
    utc: ["Asia/Krasnoyarsk"],
    utcData: "Asia/Krasnoyarsk",
  },
  {
    value: "Singapore Standard Time",
    abbr: "MPST",
    offset: 8,
    isdst: false,
    text: "(UTC+08:00) Kuala Lumpur, Singapore",
    utc: [
      "Asia/Brunei",
      "Asia/Kuala_Lumpur",
      "Asia/Kuching",
      "Asia/Makassar",
      "Asia/Manila",
      "Asia/Singapore",
      "Etc/GMT-8",
    ],
    utcData: "Asia/Brunei",
  },
  {
    value: "W. Australia Standard Time",
    abbr: "WAST",
    offset: 8,
    isdst: false,
    text: "(UTC+08:00) Perth",
    utc: ["Antarctica/Casey", "Australia/Perth"],
    utcData: "Antarctica/Casey",
  },
  {
    value: "Taipei Standard Time",
    abbr: "TST",
    offset: 8,
    isdst: false,
    text: "(UTC+08:00) Taipei",
    utc: ["Asia/Taipei"],
    utcData: "Asia/Taipei",
  },
  {
    value: "Ulaanbaatar Standard Time",
    abbr: "UST",
    offset: 8,
    isdst: false,
    text: "(UTC+08:00) Ulaanbaatar",
    utc: ["Asia/Choibalsan", "Asia/Ulaanbaatar"],
    utcData: "Asia/Choibalsan",
  },
  {
    value: "North Asia East Standard Time",
    abbr: "NAEST",
    offset: 8,
    isdst: false,
    text: "(UTC+08:00) Irkutsk",
    utc: ["Asia/Irkutsk"],
    utcData: "Asia/Irkutsk",
  },
  {
    value: "Japan Standard Time",
    abbr: "JST",
    offset: 9,
    isdst: false,
    text: "(UTC+09:00) Osaka, Sapporo, Tokyo",
    utc: [
      "Asia/Dili",
      "Asia/Jayapura",
      "Asia/Tokyo",
      "Etc/GMT-9",
      "Pacific/Palau",
    ],
    utcData: "Asia/Dili",
  },
  {
    value: "Korea Standard Time",
    abbr: "KST",
    offset: 9,
    isdst: false,
    text: "(UTC+09:00) Seoul",
    utc: ["Asia/Pyongyang", "Asia/Seoul"],
    utcData: "Asia/Pyongyang",
  },
  {
    value: "Cen. Australia Standard Time",
    abbr: "CAST",
    offset: 9.5,
    isdst: false,
    text: "(UTC+09:30) Adelaide",
    utc: ["Australia/Adelaide", "Australia/Broken_Hill"],
    utcData: "Australia/Adelaide",
  },
  {
    value: "AUS Central Standard Time",
    abbr: "ACST",
    offset: 9.5,
    isdst: false,
    text: "(UTC+09:30) Darwin",
    utc: ["Australia/Darwin"],
    utcData: "Australia/Darwin",
  },
  {
    value: "E. Australia Standard Time",
    abbr: "EAST",
    offset: 10,
    isdst: false,
    text: "(UTC+10:00) Brisbane",
    utc: ["Australia/Brisbane", "Australia/Lindeman"],
    utcData: "Australia/Brisbane",
  },
  {
    value: "AUS Eastern Standard Time",
    abbr: "AEST",
    offset: 10,
    isdst: false,
    text: "(UTC+10:00) Canberra, Melbourne, Sydney",
    utc: ["Australia/Melbourne", "Australia/Sydney"],
    utcData: "Australia/Melbourne",
  },
  {
    value: "West Pacific Standard Time",
    abbr: "WPST",
    offset: 10,
    isdst: false,
    text: "(UTC+10:00) Guam, Port Moresby",
    utc: [
      "Antarctica/DumontDUrville",
      "Etc/GMT-10",
      "Pacific/Guam",
      "Pacific/Port_Moresby",
      "Pacific/Saipan",
      "Pacific/Truk",
    ],
    utcData: "Antarctica/DumontDUrville",
  },
  {
    value: "Tasmania Standard Time",
    abbr: "TST",
    offset: 10,
    isdst: false,
    text: "(UTC+10:00) Hobart",
    utc: ["Australia/Currie", "Australia/Hobart"],
    utcData: "Australia/Currie",
  },
  {
    value: "Yakutsk Standard Time",
    abbr: "YST",
    offset: 9,
    isdst: false,
    text: "(UTC+09:00) Yakutsk",
    utc: ["Asia/Chita", "Asia/Khandyga", "Asia/Yakutsk"],
    utcData: "Asia/Chita",
  },
  {
    value: "Central Pacific Standard Time",
    abbr: "CPST",
    offset: 11,
    isdst: false,
    text: "(UTC+11:00) Solomon Is., New Caledonia",
    utc: [
      "Antarctica/Macquarie",
      "Etc/GMT-11",
      "Pacific/Efate",
      "Pacific/Guadalcanal",
      "Pacific/Kosrae",
      "Pacific/Noumea",
      "Pacific/Ponape",
    ],
    utcData: "Antarctica/Macquarie",
  },
  {
    value: "Vladivostok Standard Time",
    abbr: "VST",
    offset: 11,
    isdst: false,
    text: "(UTC+11:00) Vladivostok",
    utc: ["Asia/Sakhalin", "Asia/Ust-Nera", "Asia/Vladivostok"],
    utcData: "Asia/Sakhalin",
  },
  {
    value: "New Zealand Standard Time",
    abbr: "NZST",
    offset: 12,
    isdst: false,
    text: "(UTC+12:00) Auckland, Wellington",
    utc: ["Antarctica/McMurdo", "Pacific/Auckland"],
    utcData: "Antarctica/McMurdo",
  },
  {
    value: "UTC+12",
    abbr: "U",
    offset: 12,
    isdst: false,
    text: "(UTC+12:00) Coordinated Universal Time+12",
    utc: [
      "Etc/GMT-12",
      "Pacific/Funafuti",
      "Pacific/Kwajalein",
      "Pacific/Majuro",
      "Pacific/Nauru",
      "Pacific/Tarawa",
      "Pacific/Wake",
      "Pacific/Wallis",
    ],
    utcData: "Etc/GMT-12",
  },
  {
    value: "Fiji Standard Time",
    abbr: "FST",
    offset: 12,
    isdst: false,
    text: "(UTC+12:00) Fiji",
    utc: ["Pacific/Fiji"],
    utcData: "Pacific/Fiji",
  },
  {
    value: "Magadan Standard Time",
    abbr: "MST",
    offset: 12,
    isdst: false,
    text: "(UTC+12:00) Magadan",
    utc: [
      "Asia/Anadyr",
      "Asia/Kamchatka",
      "Asia/Magadan",
      "Asia/Srednekolymsk",
    ],
    utcData: "Asia/Anadyr",
  },
  {
    value: "Kamchatka Standard Time",
    abbr: "KDT",
    offset: 13,
    isdst: true,
    text: "(UTC+12:00) Petropavlovsk-Kamchatsky - Old",
    utc: ["Asia/Kamchatka"],
    utcData: "Asia/Kamchatka",
  },
  {
    value: "Tonga Standard Time",
    abbr: "TST",
    offset: 13,
    isdst: false,
    text: "(UTC+13:00) Nuku'alofa",
    utc: [
      "Etc/GMT-13",
      "Pacific/Enderbury",
      "Pacific/Fakaofo",
      "Pacific/Tongatapu",
    ],
    utcData: "Etc/GMT-13",
  },
  {
    value: "Samoa Standard Time",
    abbr: "SST",
    offset: 13,
    isdst: false,
    text: "(UTC+13:00) Samoa",
    utc: ["Pacific/Apia"],
    utcData: "Pacific/Apia",
  },
];

const newTimezones = [
  {
    identifier: "America/Los_Angeles",
    current_offset: -25200,
    standard_offset: -28800,
    name: "Pacific Time - US & Canada",
    group: "US/Canada",
    standard_title: "Pacific Time - US & Canada",
  },
  {
    identifier: "America/Denver",
    current_offset: -21600,
    standard_offset: -25200,
    name: "Mountain Time - US & Canada",
    group: "US/Canada",
    standard_title: "Mountain Time - US & Canada",
  },
  {
    identifier: "America/Chicago",
    current_offset: -18000,
    standard_offset: -21600,
    name: "Central Time - US & Canada",
    group: "US/Canada",
    standard_title: "Central Time - US & Canada",
  },
  {
    identifier: "America/New_York",
    current_offset: -14400,
    standard_offset: -18000,
    name: "Eastern Time - US & Canada",
    group: "US/Canada",
    standard_title: "Eastern Time - US & Canada",
  },
  {
    identifier: "America/Adak",
    current_offset: -32400,
    standard_offset: -36000,
    name: "America/Adak",
    group: "America",
    standard_title: "America/Adak",
  },
  {
    identifier: "America/Anchorage",
    current_offset: -28800,
    standard_offset: -32400,
    name: "Alaska Time",
    group: "US/Canada",
    standard_title: "Alaska Time",
  },
  {
    identifier: "America/Argentina/Buenos_Aires",
    current_offset: -10800,
    standard_offset: -10800,
    name: "Buenos Aires Time",
    group: "America",
    standard_title: "Buenos Aires Time",
  },
  {
    identifier: "America/Asuncion",
    current_offset: -14400,
    standard_offset: -14400,
    name: "Asuncion Time",
    group: "America",
    standard_title: "Asuncion Time",
  },
  {
    identifier: "America/Bogota",
    current_offset: -18000,
    standard_offset: -18000,
    name: "Bogota, Jamaica, Lima Time",
    group: "America",
    standard_title: "Bogota, Jamaica, Lima Time",
  },
  {
    identifier: "America/Campo_Grande",
    current_offset: -14400,
    standard_offset: -14400,
    name: "America/Campo Grande",
    group: "America",
    standard_title: "America/Campo Grande",
  },
  {
    identifier: "America/Caracas",
    current_offset: -14400,
    standard_offset: -14400,
    name: "Caracas Time",
    group: "America",
    standard_title: "Caracas Time",
  },
  {
    identifier: "America/Godthab",
    current_offset: -7200,
    standard_offset: -10800,
    name: "America/Godthab",
    group: "America",
    standard_title: "America/Godthab",
  },
  {
    identifier: "America/Goose_Bay",
    current_offset: -10800,
    standard_offset: -14400,
    name: "Atlantic Time",
    group: "America",
    standard_title: "Atlantic Time",
  },
  {
    identifier: "America/Guatemala",
    current_offset: -21600,
    standard_offset: -21600,
    name: "Saskatchewan, Guatemala, Costa Rica Time",
    group: "America",
    standard_title: "Saskatchewan, Guatemala, Costa Rica Time",
  },
  {
    identifier: "America/Havana",
    current_offset: -14400,
    standard_offset: -18000,
    name: "America/Havana",
    group: "America",
    standard_title: "America/Havana",
  },
  {
    identifier: "America/Mazatlan",
    current_offset: -21600,
    standard_offset: -25200,
    name: "America/Mazatlan",
    group: "America",
    standard_title: "America/Mazatlan",
  },
  {
    identifier: "America/Mexico_City",
    current_offset: -18000,
    standard_offset: -21600,
    name: "Mexico City Time",
    group: "America",
    standard_title: "Mexico City Time",
  },
  {
    identifier: "America/Montevideo",
    current_offset: -10800,
    standard_offset: -10800,
    name: "Montevideo Time",
    group: "America",
    standard_title: "Montevideo Time",
  },
  {
    identifier: "America/Miquelon",
    current_offset: -7200,
    standard_offset: -10800,
    name: "America/Miquelon",
    group: "America",
    standard_title: "America/Miquelon",
  },
  {
    identifier: "America/Noronha",
    current_offset: -7200,
    standard_offset: -7200,
    name: "America/Noronha",
    group: "America",
    standard_title: "America/Noronha",
  },
  {
    identifier: "America/Phoenix",
    current_offset: -25200,
    standard_offset: -25200,
    name: "Arizona, Yukon Time",
    group: "US/Canada",
    standard_title: "Arizona, Yukon Time",
  },
  {
    identifier: "America/Santiago",
    current_offset: -14400,
    standard_offset: -14400,
    name: "Santiago Time",
    group: "America",
    standard_title: "Santiago Time",
  },
  {
    identifier: "America/Santa_Isabel",
    current_offset: -25200,
    standard_offset: -28800,
    name: "America/Santa Isabel",
    group: "America",
    standard_title: "America/Santa Isabel",
  },
  {
    identifier: "America/Santo_Domingo",
    current_offset: -14400,
    standard_offset: -14400,
    name: "Atlantic Standard Time",
    group: "America",
    standard_title: "Atlantic Standard Time",
  },
  {
    identifier: "America/Sao_Paulo",
    current_offset: -10800,
    standard_offset: -10800,
    name: "Brasilia Time",
    group: "America",
    standard_title: "Brasilia Time",
  },
  {
    identifier: "America/St_Johns",
    current_offset: -9000,
    standard_offset: -12600,
    name: "Newfoundland Time",
    group: "US/Canada",
    standard_title: "Newfoundland Time",
  },
  {
    identifier: "Africa/Cairo",
    current_offset: 7200,
    standard_offset: 7200,
    name: "Africa/Cairo",
    group: "Africa",
    standard_title: "Africa/Cairo",
  },
  {
    identifier: "Africa/Johannesburg",
    current_offset: 7200,
    standard_offset: 7200,
    name: "Central Africa Time",
    group: "Africa",
    standard_title: "Central Africa Time",
  },
  {
    identifier: "Africa/Lagos",
    current_offset: 3600,
    standard_offset: 3600,
    name: "West Africa Time",
    group: "Africa",
    standard_title: "West Africa Time",
  },
  {
    identifier: "Africa/Windhoek",
    current_offset: 7200,
    standard_offset: 7200,
    name: "Africa/Windhoek",
    group: "Africa",
    standard_title: "Africa/Windhoek",
  },
  {
    identifier: "Asia/Amman",
    current_offset: 10800,
    standard_offset: 7200,
    name: "Jordan Time",
    group: "Asia",
    standard_title: "Jordan Time",
  },
  {
    identifier: "Asia/Baghdad",
    current_offset: 10800,
    standard_offset: 10800,
    name: "Baghdad, East Africa Time",
    group: "Asia",
    standard_title: "Baghdad, East Africa Time",
  },
  {
    identifier: "Asia/Baku",
    current_offset: 14400,
    standard_offset: 14400,
    name: "Asia/Baku",
    group: "Asia",
    standard_title: "Asia/Baku",
  },
  {
    identifier: "Asia/Beirut",
    current_offset: 10800,
    standard_offset: 7200,
    name: "Lebanon Time",
    group: "Asia",
    standard_title: "Lebanon Time",
  },
  {
    identifier: "Asia/Damascus",
    current_offset: 10800,
    standard_offset: 7200,
    name: "Syria Time",
    group: "Asia",
    standard_title: "Syria Time",
  },
  {
    identifier: "Asia/Dhaka",
    current_offset: 21600,
    standard_offset: 21600,
    name: "Asia/Dhaka",
    group: "Asia",
    standard_title: "Asia/Dhaka",
  },
  {
    identifier: "Asia/Dubai",
    current_offset: 14400,
    standard_offset: 14400,
    name: "Dubai Time",
    group: "Asia",
    standard_title: "Dubai Time",
  },
  {
    identifier: "Asia/Gaza",
    current_offset: 10800,
    standard_offset: 7200,
    name: "Asia/Gaza",
    group: "Asia",
    standard_title: "Asia/Gaza",
  },
  {
    identifier: "Asia/Irkutsk",
    current_offset: 28800,
    standard_offset: 28800,
    name: "Asia/Irkutsk",
    group: "Asia",
    standard_title: "Asia/Irkutsk",
  },
  {
    identifier: "Asia/Jakarta",
    current_offset: 25200,
    standard_offset: 25200,
    name: "Indochina Time",
    group: "Asia",
    standard_title: "Indochina Time",
  },
  {
    identifier: "Asia/Jerusalem",
    current_offset: 10800,
    standard_offset: 7200,
    name: "Israel Time",
    group: "Asia",
    standard_title: "Israel Time",
  },
  {
    identifier: "Asia/Kabul",
    current_offset: 16200,
    standard_offset: 16200,
    name: "Kabul Time",
    group: "Asia",
    standard_title: "Kabul Time",
  },
  {
    identifier: "Asia/Kamchatka",
    current_offset: 43200,
    standard_offset: 43200,
    name: "Pacific/Majuro",
    group: "Asia",
    standard_title: "Pacific/Majuro",
  },
  {
    identifier: "Asia/Karachi",
    current_offset: 18000,
    standard_offset: 18000,
    name: "Pakistan, Maldives Time",
    group: "Asia",
    standard_title: "Pakistan, Maldives Time",
  },
  {
    identifier: "Asia/Kathmandu",
    current_offset: 20700,
    standard_offset: 20700,
    name: "Kathmandu Time",
    group: "Asia",
    standard_title: "Kathmandu Time",
  },
  {
    identifier: "Asia/Kolkata",
    current_offset: 19800,
    standard_offset: 19800,
    name: "India, Sri Lanka Time",
    group: "Asia",
    standard_title: "India, Sri Lanka Time",
  },
  {
    identifier: "Asia/Krasnoyarsk",
    current_offset: 25200,
    standard_offset: 25200,
    name: "Krasnoyarsk Time",
    group: "Asia",
    standard_title: "Krasnoyarsk Time",
  },
  {
    identifier: "Asia/Omsk",
    current_offset: 21600,
    standard_offset: 21600,
    name: "Asia/Omsk",
    group: "Asia",
    standard_title: "Asia/Omsk",
  },
  {
    identifier: "Asia/Rangoon",
    current_offset: 23400,
    standard_offset: 23400,
    name: "Asia/Rangoon",
    group: "Asia",
    standard_title: "Asia/Rangoon",
  },
  {
    identifier: "Asia/Shanghai",
    current_offset: 28800,
    standard_offset: 28800,
    name: "China, Singapore, Perth",
    group: "Asia",
    standard_title: "China, Singapore, Perth",
  },
  {
    identifier: "Asia/Tehran",
    current_offset: 16200,
    standard_offset: 12600,
    name: "Tehran Time",
    group: "Asia",
    standard_title: "Tehran Time",
  },
  {
    identifier: "Asia/Tokyo",
    current_offset: 32400,
    standard_offset: 32400,
    name: "Japan, Korea Time",
    group: "Asia",
    standard_title: "Japan, Korea Time",
  },
  {
    identifier: "Asia/Vladivostok",
    current_offset: 36000,
    standard_offset: 36000,
    name: "Asia/Vladivostok",
    group: "Asia",
    standard_title: "Asia/Vladivostok",
  },
  {
    identifier: "Asia/Yakutsk",
    current_offset: 32400,
    standard_offset: 32400,
    name: "Asia/Yakutsk",
    group: "Asia",
    standard_title: "Asia/Yakutsk",
  },
  {
    identifier: "Asia/Yekaterinburg",
    current_offset: 18000,
    standard_offset: 18000,
    name: "Yekaterinburg Time",
    group: "Asia",
    standard_title: "Yekaterinburg Time",
  },
  {
    identifier: "Asia/Yerevan",
    current_offset: 14400,
    standard_offset: 14400,
    name: "Asia/Yerevan",
    group: "Asia",
    standard_title: "Asia/Yerevan",
  },
  {
    identifier: "Atlantic/Azores",
    current_offset: 0,
    standard_offset: -3600,
    name: "Azores Time",
    group: "Atlantic",
    standard_title: "Azores Time",
  },
  {
    identifier: "Atlantic/Cape_Verde",
    current_offset: -3600,
    standard_offset: -3600,
    name: "Cape Verde Time",
    group: "Atlantic",
    standard_title: "Cape Verde Time",
  },
  {
    identifier: "Australia/Adelaide",
    current_offset: 34200,
    standard_offset: 34200,
    name: "Adelaide Time",
    group: "Australia",
    standard_title: "Adelaide Time",
  },
  {
    identifier: "Australia/Brisbane",
    current_offset: 36000,
    standard_offset: 36000,
    name: "Brisbane Time",
    group: "Australia",
    standard_title: "Brisbane Time",
  },
  {
    identifier: "Australia/Darwin",
    current_offset: 34200,
    standard_offset: 34200,
    name: "Australia/Darwin",
    group: "Australia",
    standard_title: "Australia/Darwin",
  },
  {
    identifier: "Australia/Eucla",
    current_offset: 31500,
    standard_offset: 31500,
    name: "Australia/Eucla",
    group: "Australia",
    standard_title: "Australia/Eucla",
  },
  {
    identifier: "Australia/Lord_Howe",
    current_offset: 37800,
    standard_offset: 37800,
    name: "Australia/Lord Howe",
    group: "Australia",
    standard_title: "Australia/Lord Howe",
  },
  {
    identifier: "Australia/Perth",
    current_offset: 28800,
    standard_offset: 28800,
    name: "Australia/Perth",
    group: "Australia",
    standard_title: "Australia/Perth",
  },
  {
    identifier: "Australia/Sydney",
    current_offset: 36000,
    standard_offset: 36000,
    name: "Sydney, Melbourne Time",
    group: "Australia",
    standard_title: "Sydney, Melbourne Time",
  },
  {
    identifier: "UTC",
    current_offset: 0,
    standard_offset: 0,
    name: "UTC Time",
    group: "UTC",
    standard_title: "UTC Time",
  },
  {
    identifier: "Europe/Berlin",
    current_offset: 7200,
    standard_offset: 3600,
    name: "Central European Time",
    group: "Europe",
    standard_title: "Central European Time",
  },
  {
    identifier: "Europe/Helsinki",
    current_offset: 10800,
    standard_offset: 7200,
    name: "Eastern European Time",
    group: "Europe",
    standard_title: "Eastern European Time",
  },
  {
    identifier: "Europe/London",
    current_offset: 3600,
    standard_offset: 0,
    name: "UK, Ireland, Lisbon Time",
    group: "Europe",
    standard_title: "UK, Ireland, Lisbon Time",
  },
  {
    identifier: "Europe/Minsk",
    current_offset: 10800,
    standard_offset: 10800,
    name: "Minsk Time",
    group: "Europe",
    standard_title: "Minsk Time",
  },
  {
    identifier: "Europe/Moscow",
    current_offset: 10800,
    standard_offset: 10800,
    name: "Moscow Time",
    group: "Europe",
    standard_title: "Moscow Time",
  },
  {
    identifier: "Europe/Istanbul",
    current_offset: 10800,
    standard_offset: 10800,
    name: "Turkey Time",
    group: "Europe",
    standard_title: "Turkey Time",
  },
  {
    identifier: "Pacific/Apia",
    current_offset: 46800,
    standard_offset: 46800,
    name: "Pacific/Apia",
    group: "Pacific",
    standard_title: "Pacific/Apia",
  },
  {
    identifier: "Pacific/Auckland",
    current_offset: 43200,
    standard_offset: 43200,
    name: "Auckland Time",
    group: "Pacific",
    standard_title: "Auckland Time",
  },
  {
    identifier: "Pacific/Chatham",
    current_offset: 45900,
    standard_offset: 45900,
    name: "Pacific/Chatham",
    group: "Pacific",
    standard_title: "Pacific/Chatham",
  },
  {
    identifier: "Pacific/Easter",
    current_offset: -21600,
    standard_offset: -21600,
    name: "Pacific/Easter",
    group: "Pacific",
    standard_title: "Pacific/Easter",
  },
  {
    identifier: "Pacific/Fiji",
    current_offset: 43200,
    standard_offset: 43200,
    name: "Pacific/Fiji",
    group: "Pacific",
    standard_title: "Pacific/Fiji",
  },
  {
    identifier: "Pacific/Gambier",
    current_offset: -32400,
    standard_offset: -32400,
    name: "Pacific/Gambier",
    group: "Pacific",
    standard_title: "Pacific/Gambier",
  },
  {
    identifier: "Pacific/Honolulu",
    current_offset: -36000,
    standard_offset: -36000,
    name: "Hawaii Time",
    group: "US/Canada",
    standard_title: "Hawaii Time",
  },
  {
    identifier: "Pacific/Kiritimati",
    current_offset: 50400,
    standard_offset: 50400,
    name: "Pacific/Kiritimati",
    group: "Pacific",
    standard_title: "Pacific/Kiritimati",
  },
  {
    identifier: "Pacific/Majuro",
    current_offset: 43200,
    standard_offset: 43200,
    name: "Pacific/Majuro",
    group: "Pacific",
    standard_title: "Pacific/Majuro",
  },
  {
    identifier: "Pacific/Marquesas",
    current_offset: -34200,
    standard_offset: -34200,
    name: "Pacific/Marquesas",
    group: "Pacific",
    standard_title: "Pacific/Marquesas",
  },
  {
    identifier: "Pacific/Norfolk",
    current_offset: 39600,
    standard_offset: 39600,
    name: "Pacific/Norfolk",
    group: "Pacific",
    standard_title: "Pacific/Norfolk",
  },
  {
    identifier: "Pacific/Noumea",
    current_offset: 39600,
    standard_offset: 39600,
    name: "Pacific/Noumea",
    group: "Pacific",
    standard_title: "Pacific/Noumea",
  },
  {
    identifier: "Pacific/Pago_Pago",
    current_offset: -39600,
    standard_offset: -39600,
    name: "Pacific/Pago Pago",
    group: "Pacific",
    standard_title: "Pacific/Pago Pago",
  },
  {
    identifier: "Pacific/Pitcairn",
    current_offset: -28800,
    standard_offset: -28800,
    name: "Pacific/Pitcairn",
    group: "Pacific",
    standard_title: "Pacific/Pitcairn",
  },
  {
    identifier: "Pacific/Tarawa",
    current_offset: 43200,
    standard_offset: 43200,
    name: "Pacific/Tarawa",
    group: "Pacific",
    standard_title: "Pacific/Tarawa",
  },
  {
    identifier: "Pacific/Tongatapu",
    current_offset: 46800,
    standard_offset: 46800,
    name: "Pacific/Tongatapu",
    group: "Pacific",
    standard_title: "Pacific/Tongatapu",
  },
  {
    identifier: "Asia/Calcutta",
    current_offset: 19800,
    standard_offset: 19800,
    name: "India Standard Time",
    group: "Asia",
    standard_title: "India Standard Time",
  },
];

module.exports = { timezones, newTimezones };
